interface WeatherStationData {
    PASSKEY: string
    stationtype: string
    dateutc: string,
    tempinf: number,
    humidityin: number,
    baromrelin: number,
    baromabsin: number,
    tempf: number,
    humidity: number,
    winddir: number,
    winddir_avg10m: number,
    windspeedmph: number,
    windspdmph_avg10m: number,
    windgustmph: number,
    maxdailygust: number,
    rainratein: number,
    eventrainin: number,
    hourlyrainin: number,
    dailyrainin: number,
    weeklyrainin: number,
    monthlyrainin: number,
    yearlyrainin: number,
    solarradiation: number,
    uv: number,
    model: number,
    temp2f?: number,
    humidity2?: number,
    temp3f?: number,
    humidity3?: number,
    temp4f?: number,
    humidity4?: number,
    temp5f?: number,
    humidity5?: number,
    temp6f?: number,
    humidity6?: number,
    temp7f?: number,
    humidity7?: number,
    temp8f?: number,
    humidity8?: number,
}


